sonar.organization=bladibap
sonar.projectKey=bladiBap_ddd-proyect

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/src/Infrastructure/Persistence/Migrations/**,**/src/Test/**,**/src/Common/**

sonar.tests=src/Test
sonar.test.inclusions=src/Test/**/*.test.ts, src/Test/**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
