sonar.organization=bladibap
sonar.projectKey=bladiBap_ddd-proyect

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts, **/*.test.ts
sonar.exclusions=**/node_modules/**, **/dist/**, **/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
